plugins:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
  TargetRubyVersion: 3.4

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

Style/OptionHash:
  Enabled: true

Layout/LineLength:
  Max: 88

Naming/InclusiveLanguage:
  Enabled: true
  CheckStrings: true

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

RSpec/NestedGroups:
  Max: 7

RSpec/MultipleExpectations:
  Max: 5
